
package StudentPaymentSystems;

import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class AdminLogIn extends javax.swing.JFrame {

 
 
    public AdminLogIn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMin1 = new javax.swing.JPanel();
        lblLogin1 = new javax.swing.JLabel();
        lblClose1 = new javax.swing.JLabel();
        LogInLabel3Min1 = new javax.swing.JLabel();
        LogInPanel3 = new javax.swing.JPanel();
        LogInlabel4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbxUserName1 = new javax.swing.JTextField();
        tbxPassword1 = new javax.swing.JPasswordField();
        btnLogIn1 = new javax.swing.JButton();
        tbxCancel1 = new javax.swing.JButton();
        lblMin = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        LogInLabel3Min = new javax.swing.JLabel();
        LogInPanel2 = new javax.swing.JPanel();
        LogInlabel3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbxUserName = new javax.swing.JTextField();
        tbxPassword = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        tbxCancel = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();

        lblMin1.setBackground(new java.awt.Color(0, 204, 255));

        lblLogin1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLogin1.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin1.setText("Log In");

        lblClose1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblClose1.setForeground(new java.awt.Color(255, 255, 255));
        lblClose1.setText("X");
        lblClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose1MouseClicked(evt);
            }
        });

        LogInLabel3Min1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LogInLabel3Min1.setForeground(new java.awt.Color(255, 255, 255));
        LogInLabel3Min1.setText("-");
        LogInLabel3Min1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogInLabel3Min1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInLabel3Min1MouseClicked(evt);
            }
        });

        LogInPanel3.setBackground(new java.awt.Color(0, 0, 51));

        LogInlabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LogInlabel4.setForeground(new java.awt.Color(255, 255, 255));
        LogInlabel4.setText("Username:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");

        tbxUserName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbxPassword1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbxPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxPassword1ActionPerformed(evt);
            }
        });

        btnLogIn1.setBackground(new java.awt.Color(0, 204, 204));
        btnLogIn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogIn1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn1.setText("LogIn");
        btnLogIn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogIn1MouseClicked(evt);
            }
        });
        btnLogIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogIn1ActionPerformed(evt);
            }
        });

        tbxCancel1.setBackground(new java.awt.Color(255, 0, 0));
        tbxCancel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbxCancel1.setForeground(new java.awt.Color(255, 255, 255));
        tbxCancel1.setText("Cancel");
        tbxCancel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbxCancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxCancel1MouseClicked(evt);
            }
        });
        tbxCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxCancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LogInPanel3Layout = new javax.swing.GroupLayout(LogInPanel3);
        LogInPanel3.setLayout(LogInPanel3Layout);
        LogInPanel3Layout.setHorizontalGroup(
            LogInPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPanel3Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(LogInPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogInlabel4)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(LogInPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(LogInPanel3Layout.createSequentialGroup()
                        .addComponent(tbxCancel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(btnLogIn1))
                    .addComponent(tbxUserName1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(tbxPassword1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        LogInPanel3Layout.setVerticalGroup(
            LogInPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(LogInPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInlabel4)
                    .addComponent(tbxUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(LogInPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tbxPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(LogInPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogIn1)
                    .addComponent(tbxCancel1))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout lblMin1Layout = new javax.swing.GroupLayout(lblMin1);
        lblMin1.setLayout(lblMin1Layout);
        lblMin1Layout.setHorizontalGroup(
            lblMin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogInPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lblMin1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogin1)
                .addGap(147, 147, 147)
                .addComponent(LogInLabel3Min1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClose1)
                .addGap(23, 23, 23))
        );
        lblMin1Layout.setVerticalGroup(
            lblMin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMin1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(lblMin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogInLabel3Min1)
                    .addComponent(lblClose1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(LogInPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblMin.setBackground(new java.awt.Color(0, 204, 255));

        lblClose.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        LogInLabel3Min.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LogInLabel3Min.setForeground(new java.awt.Color(255, 255, 255));
        LogInLabel3Min.setText("-");
        LogInLabel3Min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogInLabel3Min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInLabel3MinMouseClicked(evt);
            }
        });

        LogInPanel2.setBackground(new java.awt.Color(0, 0, 51));

        LogInlabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LogInlabel3.setForeground(new java.awt.Color(255, 255, 255));
        LogInlabel3.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        tbxUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbxPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxPasswordActionPerformed(evt);
            }
        });

        btnLogIn.setBackground(new java.awt.Color(0, 204, 204));
        btnLogIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("LogIn");
        btnLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogInMouseClicked(evt);
            }
        });
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        tbxCancel.setBackground(new java.awt.Color(255, 0, 0));
        tbxCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbxCancel.setForeground(new java.awt.Color(255, 255, 255));
        tbxCancel.setText("Reset");
        tbxCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbxCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxCancelMouseClicked(evt);
            }
        });
        tbxCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LogInPanel2Layout = new javax.swing.GroupLayout(LogInPanel2);
        LogInPanel2.setLayout(LogInPanel2Layout);
        LogInPanel2Layout.setHorizontalGroup(
            LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPanel2Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInPanel2Layout.createSequentialGroup()
                        .addGroup(LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInPanel2Layout.createSequentialGroup()
                                .addComponent(LogInlabel3)
                                .addGap(58, 58, 58)
                                .addComponent(tbxUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(69, 69, 69)
                                .addComponent(tbxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInPanel2Layout.createSequentialGroup()
                        .addComponent(tbxCancel)
                        .addGap(92, 92, 92)
                        .addComponent(btnLogIn)
                        .addGap(210, 210, 210))))
        );
        LogInPanel2Layout.setVerticalGroup(
            LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInlabel3)
                    .addComponent(tbxUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(111, 111, 111)
                .addGroup(LogInPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogIn)
                    .addComponent(tbxCancel))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setIcon(new javax.swing.ImageIcon("E:\\Java Project\\StudentPaymentSystem\\nbproject\\Images\\LogIn.png")); // NOI18N
        lblLogin.setText("Log In");

        javax.swing.GroupLayout lblMinLayout = new javax.swing.GroupLayout(lblMin);
        lblMin.setLayout(lblMinLayout);
        lblMinLayout.setHorizontalGroup(
            lblMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMinLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblMinLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogInLabel3Min, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblClose)
                        .addGap(23, 23, 23))
                    .addGroup(lblMinLayout.createSequentialGroup()
                        .addComponent(LogInPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        lblMinLayout.setVerticalGroup(
            lblMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMinLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(lblMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInLabel3Min)
                    .addComponent(lblClose))
                .addGroup(lblMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblMinLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblMinLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(LogInPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxPasswordActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void LogInLabel3MinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInLabel3MinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_LogInLabel3MinMouseClicked

    private void btnLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseClicked
        
    }//GEN-LAST:event_btnLogInMouseClicked

    private void tbxCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxCancelMouseClicked
        
    }//GEN-LAST:event_tbxCancelMouseClicked

    private void tbxCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxCancelActionPerformed
      StudentLogIn ad=new StudentLogIn();
        ad.setVisible(true);
        ad.pack();
        ad.setLocationRelativeTo(null);
        ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_tbxCancelActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
  String uname= tbxUserName.getText();
  String pass= tbxPassword.getText();
  if (pass.contains("123")&& (uname.contains("sohel"))){
      AdminMenu ad=new AdminMenu();
        ad.setVisible(true);
        ad.pack();
        ad.setLocationRelativeTo(null);
        ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
  }
  else{
      JOptionPane.showMessageDialog(null,"Wrong User Name or Password ");
       AdminLogIn reg = new AdminLogIn();
       reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
  }
        
    }//GEN-LAST:event_btnLogInActionPerformed

    private void lblClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblClose1MouseClicked

    private void LogInLabel3Min1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInLabel3Min1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInLabel3Min1MouseClicked

    private void tbxPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxPassword1ActionPerformed

    private void btnLogIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogIn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogIn1MouseClicked

    private void btnLogIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogIn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogIn1ActionPerformed

    private void tbxCancel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxCancel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxCancel1MouseClicked

    private void tbxCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxCancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxCancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogInLabel3Min;
    private javax.swing.JLabel LogInLabel3Min1;
    private javax.swing.JPanel LogInPanel2;
    private javax.swing.JPanel LogInPanel3;
    private javax.swing.JLabel LogInlabel3;
    private javax.swing.JLabel LogInlabel4;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnLogIn1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblClose1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JPanel lblMin;
    private javax.swing.JPanel lblMin1;
    private javax.swing.JButton tbxCancel;
    private javax.swing.JButton tbxCancel1;
    private javax.swing.JPasswordField tbxPassword;
    private javax.swing.JPasswordField tbxPassword1;
    private javax.swing.JTextField tbxUserName;
    private javax.swing.JTextField tbxUserName1;
    // End of variables declaration//GEN-END:variables
}
