
package StudentPaymentSystems;




import javax.swing.JFrame;

import javax.swing.JOptionPane;

public class StudentLogIn extends javax.swing.JFrame {

    /**
     * Creates new form StudentLogIn
     */
    public StudentLogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMin3 = new javax.swing.JPanel();
        lblClose3 = new javax.swing.JLabel();
        LogInLabel3Min3 = new javax.swing.JLabel();
        LogInPanel5 = new javax.swing.JPanel();
        LogInlabel6 = new javax.swing.JLabel();
        passlbl = new javax.swing.JLabel();
        tbxUserName3 = new javax.swing.JTextField();
        tbxPassword3 = new javax.swing.JPasswordField();
        btnLogIn3 = new javax.swing.JButton();
        tbxCancel3 = new javax.swing.JButton();
        lblLogin3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lblMin3.setBackground(new java.awt.Color(0, 204, 255));

        lblClose3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblClose3.setForeground(new java.awt.Color(255, 255, 255));
        lblClose3.setText("X");
        lblClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose3MouseClicked(evt);
            }
        });

        LogInLabel3Min3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LogInLabel3Min3.setForeground(new java.awt.Color(255, 255, 255));
        LogInLabel3Min3.setText("-");
        LogInLabel3Min3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogInLabel3Min3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInLabel3Min3MouseClicked(evt);
            }
        });

        LogInPanel5.setBackground(new java.awt.Color(0, 0, 51));

        LogInlabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LogInlabel6.setForeground(new java.awt.Color(255, 255, 255));
        LogInlabel6.setText("Student Id");

        passlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passlbl.setForeground(new java.awt.Color(255, 255, 255));
        passlbl.setText("Password:");

        tbxUserName3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbxPassword3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbxPassword3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxPassword3ActionPerformed(evt);
            }
        });

        btnLogIn3.setBackground(new java.awt.Color(0, 204, 204));
        btnLogIn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogIn3.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn3.setText("LogIn");
        btnLogIn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogIn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogIn3MouseClicked(evt);
            }
        });
        btnLogIn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogIn3ActionPerformed(evt);
            }
        });

        tbxCancel3.setBackground(new java.awt.Color(255, 0, 0));
        tbxCancel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbxCancel3.setForeground(new java.awt.Color(255, 255, 255));
        tbxCancel3.setText("Reset");
        tbxCancel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbxCancel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxCancel3MouseClicked(evt);
            }
        });
        tbxCancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxCancel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LogInPanel5Layout = new javax.swing.GroupLayout(LogInPanel5);
        LogInPanel5.setLayout(LogInPanel5Layout);
        LogInPanel5Layout.setHorizontalGroup(
            LogInPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPanel5Layout.createSequentialGroup()
                .addGroup(LogInPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInPanel5Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(tbxCancel3)
                        .addGap(87, 87, 87)
                        .addComponent(btnLogIn3))
                    .addGroup(LogInPanel5Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(LogInPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LogInPanel5Layout.createSequentialGroup()
                                .addComponent(LogInlabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbxUserName3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LogInPanel5Layout.createSequentialGroup()
                                .addComponent(passlbl)
                                .addGap(38, 38, 38)
                                .addComponent(tbxPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        LogInPanel5Layout.setVerticalGroup(
            LogInPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPanel5Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(LogInPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInlabel6)
                    .addComponent(tbxUserName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(LogInPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passlbl)
                    .addComponent(tbxPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(LogInPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxCancel3)
                    .addComponent(btnLogIn3))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        lblLogin3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLogin3.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin3.setIcon(new javax.swing.ImageIcon("E:\\Java Project\\StudentPaymentSystem\\nbproject\\Images\\LogIn.png")); // NOI18N
        lblLogin3.setText("Log In");

        javax.swing.GroupLayout lblMin3Layout = new javax.swing.GroupLayout(lblMin3);
        lblMin3.setLayout(lblMin3Layout);
        lblMin3Layout.setHorizontalGroup(
            lblMin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMin3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogInLabel3Min3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClose3)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblMin3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblLogin3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(LogInPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lblMin3Layout.setVerticalGroup(
            lblMin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMin3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(lblMin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInLabel3Min3)
                    .addComponent(lblClose3))
                .addGroup(lblMin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblMin3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LogInPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblMin3Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblLogin3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMin3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMin3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblClose3MouseClicked

    private void LogInLabel3Min3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInLabel3Min3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_LogInLabel3Min3MouseClicked

    private void tbxPassword3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxPassword3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxPassword3ActionPerformed

    private void btnLogIn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogIn3MouseClicked
        AdminMenu ad=new AdminMenu();
        ad.setVisible(true);
        ad.pack();
        ad.setLocationRelativeTo(null);
        ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnLogIn3MouseClicked

    private void btnLogIn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogIn3ActionPerformed
        String uname= tbxUserName3.getText();
        String pass= tbxPassword3.getText();
        if (pass.contains("123")&& (uname.contains("172-35-2134"))){
        StudentMenu ad =new StudentMenu();
        ad.setVisible(true);
        ad.pack();
        ad.setLocationRelativeTo(null);
        ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
  }
  else{
      JOptionPane.showMessageDialog(null,"Wrong ID or Password ");
      StudentLogIn ad=new StudentLogIn();
        ad.setVisible(true);
        ad.pack();
        ad.setLocationRelativeTo(null);
        ad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
  }
    }//GEN-LAST:event_btnLogIn3ActionPerformed

    private void tbxCancel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxCancel3MouseClicked

    }//GEN-LAST:event_tbxCancel3MouseClicked

    private void tbxCancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxCancel3ActionPerformed
       
    }//GEN-LAST:event_tbxCancel3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogInLabel3Min3;
    private javax.swing.JPanel LogInPanel5;
    private javax.swing.JLabel LogInlabel6;
    private javax.swing.JButton btnLogIn3;
    private javax.swing.JLabel lblClose3;
    private javax.swing.JLabel lblLogin3;
    private javax.swing.JPanel lblMin3;
    private javax.swing.JLabel passlbl;
    private javax.swing.JButton tbxCancel3;
    private javax.swing.JPasswordField tbxPassword3;
    private javax.swing.JTextField tbxUserName3;
    // End of variables declaration//GEN-END:variables
}
