package bank.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class registerForm extends javax.swing.JFrame {

    /**
     * Creates new form registerForm
     */
    public registerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        nidField = new javax.swing.JTextField();
        acField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        retypePasswordField = new javax.swing.JPasswordField();
        rbtnmale = new javax.swing.JRadioButton();
        rbtnfemale = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        dobField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 30));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 47)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create a Bank Account");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 40, 962, 48);

        jLabel2.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 130, 150, 14);

        jLabel3.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 180, 140, 14);

        jLabel4.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 230, 200, 14);

        jLabel5.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 300, 100, 14);

        jLabel6.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Birth");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(140, 390, 167, 20);

        jLabel7.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(710, 130, 110, 14);

        jLabel8.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Choose A/C No");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(630, 250, 190, 14);

        jLabel9.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Create a password");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(590, 310, 231, 14);

        jLabel10.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Re-type password");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(600, 370, 224, 14);

        jLabel11.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NID number");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(650, 190, 161, 14);

        firstNameField.setBackground(new java.awt.Color(51, 51, 51));
        firstNameField.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        firstNameField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameField.setPreferredSize(new java.awt.Dimension(130, 27));
        jPanel1.add(firstNameField);
        firstNameField.setBounds(350, 120, 160, 27);

        lastNameField.setBackground(new java.awt.Color(51, 51, 51));
        lastNameField.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        lastNameField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameField.setMinimumSize(new java.awt.Dimension(130, 20));
        lastNameField.setPreferredSize(new java.awt.Dimension(130, 27));
        jPanel1.add(lastNameField);
        lastNameField.setBounds(350, 170, 160, 27);

        phoneNumberField.setBackground(new java.awt.Color(51, 51, 51));
        phoneNumberField.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        phoneNumberField.setForeground(new java.awt.Color(255, 255, 255));
        phoneNumberField.setMinimumSize(new java.awt.Dimension(130, 20));
        phoneNumberField.setPreferredSize(new java.awt.Dimension(130, 27));
        jPanel1.add(phoneNumberField);
        phoneNumberField.setBounds(350, 220, 160, 27);

        addressField.setBackground(new java.awt.Color(51, 51, 51));
        addressField.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        addressField.setForeground(new java.awt.Color(255, 255, 255));
        addressField.setPreferredSize(new java.awt.Dimension(130, 27));
        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });
        jPanel1.add(addressField);
        addressField.setBounds(870, 110, 300, 50);

        nidField.setBackground(new java.awt.Color(51, 51, 51));
        nidField.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        nidField.setForeground(new java.awt.Color(255, 255, 255));
        nidField.setPreferredSize(new java.awt.Dimension(130, 27));
        nidField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nidFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nidField);
        nidField.setBounds(870, 180, 220, 27);

        acField.setBackground(new java.awt.Color(51, 51, 51));
        acField.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        acField.setForeground(new java.awt.Color(255, 255, 255));
        acField.setPreferredSize(new java.awt.Dimension(130, 27));
        jPanel1.add(acField);
        acField.setBounds(870, 240, 200, 27);

        passwordField.setBackground(new java.awt.Color(51, 51, 51));
        passwordField.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setPreferredSize(new java.awt.Dimension(130, 27));
        jPanel1.add(passwordField);
        passwordField.setBounds(870, 300, 200, 27);

        retypePasswordField.setBackground(new java.awt.Color(51, 51, 51));
        retypePasswordField.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        retypePasswordField.setForeground(new java.awt.Color(255, 255, 255));
        retypePasswordField.setPreferredSize(new java.awt.Dimension(130, 27));
        jPanel1.add(retypePasswordField);
        retypePasswordField.setBounds(870, 360, 200, 27);

        rbtnmale.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rbtnmale);
        rbtnmale.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        rbtnmale.setForeground(new java.awt.Color(255, 255, 255));
        rbtnmale.setText("Male");
        jPanel1.add(rbtnmale);
        rbtnmale.setBounds(350, 290, 71, 21);

        rbtnfemale.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rbtnfemale);
        rbtnfemale.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        rbtnfemale.setForeground(new java.awt.Color(255, 255, 255));
        rbtnfemale.setText("Female");
        jPanel1.add(rbtnfemale);
        rbtnfemale.setBounds(350, 320, 97, 21);

        submitButton.setBackground(new java.awt.Color(255, 255, 255));
        submitButton.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(51, 51, 51));
        submitButton.setText("SUBMIT");
        submitButton.setPreferredSize(new java.awt.Dimension(200, 80));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton);
        submitButton.setBounds(590, 450, 190, 50);

        dobField.setBackground(new java.awt.Color(51, 51, 51));
        dobField.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        dobField.setForeground(new java.awt.Color(255, 255, 255));
        dobField.setPreferredSize(new java.awt.Dimension(130, 27));
        jPanel1.add(dobField);
        dobField.setBounds(350, 380, 160, 27);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("HOME");
        jButton1.setPreferredSize(new java.awt.Dimension(200, 80));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 450, 200, 50);

        resetButton.setBackground(new java.awt.Color(255, 255, 255));
        resetButton.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        resetButton.setForeground(new java.awt.Color(51, 51, 51));
        resetButton.setText("RESET");
        resetButton.setPreferredSize(new java.awt.Dimension(210, 80));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resetButton);
        resetButton.setBounds(880, 450, 160, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void nidFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nidFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nidFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        databaseConnection con = new databaseConnection();
        Connection c = con.connect();
        String firstName,lastName, phoneNumber, gender = null, dateOfBirth, address, nid, acNumber, password;
        firstName = firstNameField.getText();
        lastName = lastNameField.getText();
        phoneNumber = phoneNumberField.getText();
        if(rbtnmale.isSelected()){
            gender="Male";
        }
        else if(rbtnfemale.isSelected()){
            gender = "Female";
        }
        dateOfBirth = dobField.getText();
        address = addressField.getText();
        nid = nidField.getText();
        acNumber = acField.getText();
        password = passwordField.getText();
        if(validateFields()){
        String sql = "insert into Bank (First_Name, Last_Name, Phone_Number, Gender, Date_Of_Birth, Address, NID, AC, Password) values(?, ?, ?, ?, ?, ?, ?, ?, ?);";
        try{
            try (PreparedStatement pst = c.prepareStatement(sql)) {
                pst.setString(1, firstName);
                pst.setString(2, lastName);
                pst.setString(3, phoneNumber);
                pst.setString(4, gender);
                pst.setString(5, dateOfBirth);
                pst.setString(6, address);
                pst.setString(7, nid);
                pst.setString(8, acNumber);
                pst.setString(9, password);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "You Have Succesfully create your account. now please Login...");
            }
            c.close();
            
        }
        catch(SQLException e){
            System.out.println(e);
            
        }
       }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu mu = new menu();
        setVisible(false);
        mu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        firstNameField.setText(null);
        lastNameField.setText(null);
        passwordField.setText(null);
        retypePasswordField.setText(null);
        phoneNumberField.setText(null);
        dobField.setText(null);
        buttonGroup1.setSelected(null, rootPaneCheckingEnabled);
        addressField.setText(null);
        acField.setText(null);
        

    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new registerForm().setVisible(true);
        });
    }
    
    private boolean validateFields(){
        
        if(firstNameField.getText().isEmpty() | lastNameField.getText(). isEmpty() | phoneNumberField.getText(). isEmpty() | addressField.getText(). isEmpty() | acField.getText(). isEmpty() | dobField.getText(). isEmpty() | retypePasswordField.getText(). isEmpty() | passwordField.getText(). isEmpty()){
            JOptionPane.showMessageDialog(null, "Fields can't be empty");
            return false;
        }
        return true;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acField;
    private javax.swing.JTextField addressField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dobField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField nidField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JRadioButton rbtnfemale;
    private javax.swing.JRadioButton rbtnmale;
    private javax.swing.JButton resetButton;
    private javax.swing.JPasswordField retypePasswordField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
