/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseconnection_1;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Anonymous
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form dminHome
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddTeacher = new javax.swing.JButton();
        btnAddStudentInformation = new javax.swing.JButton();
        btnViewTeacher = new javax.swing.JButton();
        btnViewStudentInformation = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddTeacher.setBackground(new java.awt.Color(0, 153, 153));
        btnAddTeacher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddTeacher.setText("Add Teacher");
        btnAddTeacher.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 190, 36));

        btnAddStudentInformation.setBackground(new java.awt.Color(0, 153, 153));
        btnAddStudentInformation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddStudentInformation.setText("Add Student  Information");
        btnAddStudentInformation.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnAddStudentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentInformationActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddStudentInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 190, 36));

        btnViewTeacher.setBackground(new java.awt.Color(0, 153, 153));
        btnViewTeacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewTeacher.setText("View Teacher Information");
        btnViewTeacher.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnViewTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTeacherActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 190, 36));

        btnViewStudentInformation.setBackground(new java.awt.Color(0, 153, 153));
        btnViewStudentInformation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewStudentInformation.setText("View Student Information");
        btnViewStudentInformation.setMargin(new java.awt.Insets(1, 1, 1, 1));
        getContentPane().add(btnViewStudentInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 190, 36));

        btnLogout.setBackground(new java.awt.Color(102, 102, 255));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\evgeniy-koryakin-487393-unsplash copy.JPG")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherActionPerformed
        // TODO add your handling code here:
        AddTeacher call = new AddTeacher();
        setVisible(false);
        call.setVisible(true);
    }//GEN-LAST:event_btnAddTeacherActionPerformed

    private void btnAddStudentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentInformationActionPerformed
        // TODO add your handling code here:
        AddStudentInformation obj = new AddStudentInformation();
        setVisible(false);
        obj.setVisible(true);
    }//GEN-LAST:event_btnAddStudentInformationActionPerformed

    private void btnViewTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTeacherActionPerformed
        try {
            // TODO add your handling code here:
            ViewTeacherInformation obj = new ViewTeacherInformation();
            setVisible(false);
            obj.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnViewTeacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudentInformation;
    private javax.swing.JButton btnAddTeacher;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewStudentInformation;
    private javax.swing.JButton btnViewTeacher;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
